name: Feature
on:
    workflow_call:
        secrets:
            githubAccessToken:
                required: true
        inputs:
            pipelineType:
                description: Pipeline Type
                default: build
                type: string
                required: false

env:
    uniqueWorkspaceId: /u/github/workspace/${{ github.repository }}/${{ github.ref_name }}/build_f${{github.run_number }} # adding an f to before the number,
    # to avoid an error caused by repeated build numbers 
    pipelineType: ${{ inputs.pipelineType }}
    branch : ${{ github.ref_name }} 
    application: ${{ github.event.repository.name }}
    packageName: ${{github.run_id}}
    zosHostname: 9.76.61.15
    zosSFTPUser: DMJTA1@9.76.61.15
    
    UCD_Package: /u/DMJTA1/zAppBuild/scripts/PublishUCD.sh
    UCD_Deploy: /u/DMJTA1/zAppBuild/scripts/DeployUCD.sh
    UCD_Server_URL: https://9.76.61.225:8443
    UCD_AppProps: /u/DMJTA1/zAppBuild/dbb-zappbuild-final/GenappML2.properties
    UCD_AppDeployProcess: Deploy
    UCD_backendComponent: App1-Genapp-ZComponent
    UCD_APIComponent: App1-Genapp-API
    UCD_TestComponent: App1-Genapp-Test
    UCDApplication: App1-Genapp
    UCD_Dev_LPAR: 'DEV'
    UCD_Test_LPAR: 'TEST'
    UCD_Prod_LPAR: 'PROD'
    UCD_PreProd_LPAR: 'PRE-PROD'

jobs:
    Setup:
        runs-on: self-hosted
        steps:    
          - name: CI-CD pipeline parameter printout
            run: |
                echo " "
                echo "Following are the CI-CD pipeline parameters"
                echo "*******************************************"
                echo "uniqueWorkspaceId                  = ${{ env.uniqueWorkspaceId}}"
                echo "pipelineType                       = ${{ env.pipelineType}}"
                echo "branch                             = ${{ env.branch}}"
                echo "application                        = ${{ env.application}}"
                echo "packageName                        = ${{ env.packageName}}"
                echo "zosHostname                        = ${{ env.zosHostname}}"
                echo "zosSFTPUser                        = ${{ env.zosSFTPUser}}"
                 
          - name: Clone Repo to z/OS Unix System Services
            run: ssh ${{env.zosSFTPUser}} ". ./.profile && gitClone.sh -w ${{ env.uniqueWorkspaceId }} -r https://${{ secrets.githubAccessToken }}@github.com/${{ github.repository }}.git -b ${{ env.branch }}" 

    Build:
        needs:
         - Setup
        runs-on: self-hosted
        steps: 
        - name: Build git repo
          run: ssh ${{env.zosSFTPUser}} ". ./.profile && zBuilder.sh -w ${{ env.uniqueWorkspaceId }} -a ${{env.application}} -b ${{ env.branch }} -p ${{env.pipelineType}}"
        - name: Prepare logs
          if: ${{ always() }}
          run: |
            ssh ${{env.zosSFTPUser}} ". ./.profile && prepareLogs.sh -w ${{ env.uniqueWorkspaceId }}"  
            rm -rf "${{ runner.temp }}/build-logs" 
            mkdir "${{ runner.temp }}/build-logs" 
            sftp ${{env.zosSFTPUser}}:${{ env.uniqueWorkspaceId }}/*.tar "\"${{ runner.temp }}/build-logs\""
            tar -xvf "${{ runner.temp }}/build-logs/logs.tar" -C "${{ runner.temp }}/build-logs"
          shell: cmd
                  
        - name: Upload build logs
          uses: actions/upload-artifact@v4
          with:
            name: build_${{github.run_number }}                        # Name used for artifact when it is uploaded
            path: ${{ runner.temp }}/build-logs                        # Path to build logs artifacts
            retention-days: 1

    Package:
        needs:
         - Build
        runs-on: self-hosted
        steps:
         - name: Package build outputs
           run: ssh ${{env.zosSFTPUser}} ". ./.profile && ucdPackaging.sh -w ${{ env.uniqueWorkspaceId }} -v "v${{ github.run_number }}-${{ github.sha }}" -e externalRepo.properties -f packaging.properties -c App1-Genapp-ZComponent
           # run: ssh ${{env.zosSFTPUser}} ". ./.profile && packageBuildOutputs.sh -w ${{ env.uniqueWorkspaceId }} -t ${{ env.application }}.tar -a ${{ env.application }} -b ${{ env.branch }} -p ${{env.pipelineType}} -v ${{ env.packageName }} "
           # run: ${{ env.zosSFTPUser }} ${{ env.UCD_Package }} ${{ env.UCD_backendComponent }}  ${{ env.MyWorkDir }} ${{ env.UCD_AppProps }} ${{ steps.getBranch.outputs.value }}.Build.${{ github.run_number }}
           shell: cmd      
         
    Cleanup:
        needs:
          - Package
        runs-on: self-hosted
        if: always()
        steps:
          - name: Cleanup Build Environment
            run: ssh ${{ env.zosSFTPUser}} ". ./.profile && deleteWorkspace.sh -w ${{ env.uniqueWorkspaceId }}"
                
